runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

builtins:
- deferred: on

# Deplay Command:
# Run locally: `dev_appserver.py ./`
# Deploy: `gcloud app deploy app.yaml index.yaml --project uw-info2 -v 1-3-2017-07-06`
# Deploy: `gcloud app deploy app.yaml index.yaml --project uw-info1 -v 1-3-2017-07-06`
